esphome:
  name: zisterne

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
#  password: !secret ApiPassword
  encryption:
    key: !secret ApiEncryptionKey

ota:
  - platform: esphome
    password: !secret OtaPassword

wifi:
  ssid: !secret WifiSsid
  password: !secret WifiPassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Zisterne Fallback Hotspot"
    password: !secret WifiPassword

captive_portal:

# https://nachbelichtet.com/wasserstand-in-zisternen-mit-homeassistant-esphome-und-tl-136-drucksensor-messen
# nodemcu pinout: https://cdn.shopify.com/s/files/1/1509/1638/files/ESP-32_NodeMCU_Developmentboard_Pinout.pdf?v=1609851295
# i2c Bus auf D1 und D2 konfigurieren
# cxcv: nodemcu mapping
#  driver: CP210x_Universal_Windows_Driver
#  $ esphome run .\zisterne.yaml
i2c:
  id: bus_a
  sda: GPIO21 # D2
  scl: GPIO22 # D1
  scan: True

# ADC einrichten, ADDR-Pin ist auf VCC gelegt, daher Adresse 0x49
ads1115:
  - address: 0x49
    id: ads1115_49

# ADC Kanal A0 zur Messwerterfassung 
sensor:
  # Uptime-Sensor (Betriebszeit)
  - platform: uptime
    name: "${long_devicename} Betriebszeit"
    id: uptime_seconds
    update_interval: 30s

  # WLAN-Signalstärke
  - platform: wifi_signal
    name: "${long_devicename} WLAN-Signal"
    update_interval: 60s

  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    name: "height"
    id: levelraw
    update_interval: 10s
    unit_of_measurement: cm
    accuracy_decimals: 1
    icon: "mdi:car-coolant-level"
    filters:
      # ignore negative measurements
      - lambda: return max(0.0f, x);
      - calibrate_linear: # Volt -> cm
          - 0.0 -> 0.0
          - 1.37-> 185.0
      # smooth values last in filter chain
      - exponential_moving_average:
          alpha: 0.1 # Lower = smoother but slower, Higher = faster response
          send_every: 1

  # convert level to volume using measurement series
  - platform: template
    name: "volume"
    lambda: |-
      return id(levelraw).state;
    
    filters:
      - calibrate_linear: # cm -> liter
          - 0 -> 0
          - 200 -> 4539 # r=0,85m
          - 220 -> 4993 # r=0,85m
          - 225 -> 5093 # +10min/100l
          - 230 -> 5163 # +7min/70l
          - 235 -> 5208 # +4,5min/45l
          - 240 -> 5228 # +2,5min/20l
          - 245 -> 5248 # +2,5min/20l

    unit_of_measurement: l
    accuracy_decimals: 0